@startuml dto
!include themes/puml-theme-cerulean-outline.puml
skinparam backgroundColor #FFFFFF
namespace cat.udl.cig.sms.connection.datagram {
interface SMSDatagram

class GroupElementDatagram
class NeighborhoodDatagram<T>
class KeyRenewalDatagram
class BigIntegerDatagram
class CipherTextDatagram
class EndOfDatagram

SMSDatagram <|.. BigIntegerDatagram
SMSDatagram <|.. CipherTextDatagram
SMSDatagram <|.. EndOfDatagram
SMSDatagram <|.. GroupElementDatagram
SMSDatagram <|.. NeighborhoodDatagram
SMSDatagram <|.. KeyRenewalDatagram
BigIntegerDatagram : BigInteger bigInteger
CipherTextDatagram : HomomorphicCipherText ciphertext
GroupElementDatagram : GroupElement groupElement
NeighborhoodDatagram : T certificate
NeighborhoodDatagram : GroupElement groupElement
SMSDatagram : byte[] toByteArray()
}
@enduml