CRIPTO = cripto
DTO = dto
STATEMACHINE = statemachine
CONNECTION = connection
DTOSER = dtoser
CURVE = curve
SOCKET = socket
LOG = log
RECSI = recsi
BUSOM = busom

all: $(BUSOM)
	@echo "DONE"

$(BUSOM):
	java -jar plantuml.jar jlatexmath-minimal-1.0.3.jar jlm_cyrillic.jar jlm_greek.jar $(BUSOM).puml
