@startuml busom3
!include themes/puml-theme-cerulean-outline.puml
skinparam backgroundColor #FFFFFF
hnote across: Consumption transmission
loop for each message m<sub>i j</sub> in M<sub>i</sub>
    "Smart Meter M<sub>i</sub>" -> "Substation" : sendCiphertext//( c<sub>i j</sub> , d<sub>i j</sub> )//
    note left
        Reading: <latex>m_{i j}</latex>
        <latex>z_{i j} \in_R \mathbb{Z}_q^*</latex>
        <latex>E_y(g^{m_{i j} + z_j}) = (c_{i j}, d_{i j})</latex>
    end note
    Substation --> "Smart Meter M<sub>i</sub>" : c<sub>j</sub>
    note right
        <latex>C_j = (\prod_{i=1}^{n} c_{i j} , \prod_{i=1}^{n} d_{i j}) =</latex>
        <latex>(g^r , g^{m_j + z_j} \cdot y^r) = (c_j,d_j)</latex>
        with m<sub>j</sub>, <latex>m_j = \sum_{i=1}^n m_{i j}</latex>
        and z<sub>j</sub>, <latex>z_j = \sum_{i=1}^n z_{i j}</latex>
    end note
    "Smart Meter M<sub>i</sub>" -> "Substation" : T<sub>i j</sub>
    note left
        <latex>T_{i j} = c^{x_i} \cdot g^{z_{i j}}</latex>
    end note
    note right
        <latex>D_j = d \cdot (\prod_{i=1}^{n} T_{i j})^{-1} = g^{m_j}</latex>
        Computes <latex>m_j = log_g (D) </latex>
    end note
end
@enduml