BUSOM = busom
RECSI = recsi
RECSI1 = recsi1
RECSI2 = recsi2
NETWORK = network
GARRA = garra
BUSOM2 = busom2
BUSOM3 = busom3

all: $(BUSOM) $(RECSI) $(NETWORK) $(GARRRA)
	@echo "DONE"

$(BUSOM):
	java -jar plantuml.jar jlatexmath-minimal-1.0.3.jar jlm_cyrillic.jar jlm_greek.jar $(BUSOM).puml

$(RECSI):
	java -jar plantuml.jar jlatexmath-minimal-1.0.3.jar jlm_cyrillic.jar jlm_greek.jar $(RECSI).puml

$(RECSI1):
	java -jar plantuml.jar jlatexmath-minimal-1.0.3.jar jlm_cyrillic.jar jlm_greek.jar $(RECSI1).puml

$(RECSI2):
	java -jar plantuml.jar jlatexmath-minimal-1.0.3.jar jlm_cyrillic.jar jlm_greek.jar $(RECSI2).puml

$(NETWORK):
	java -jar plantuml.jar jlatexmath-minimal-1.0.3.jar jlm_cyrillic.jar jlm_greek.jar $(NETWORK).puml

$(GARRA):
	java -jar plantuml.jar jlatexmath-minimal-1.0.3.jar jlm_cyrillic.jar jlm_greek.jar $(GARRA).puml


$(BUSOM2):
	java -jar plantuml.jar jlatexmath-minimal-1.0.3.jar jlm_cyrillic.jar jlm_greek.jar $(BUSOM2).puml


$(BUSOM3):
	java -jar plantuml.jar jlatexmath-minimal-1.0.3.jar jlm_cyrillic.jar jlm_greek.jar $(BUSOM3).puml